name: Java CI with Maven

on:
  workflow_call:
    inputs:
      branch: # This is the branch that will trigger the deployment (ex: 'refs/heads/main')
        required: true
        type: string

jobs:
  compile:
    name: Compile Project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Compile the project
        run: mvn --batch-mode clean compile

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Test the project
        run: mvn --batch-mode test
      - name: Verify the project
        run: mvn --batch-mode --update-snapshots verify

  build-artifact:
    name: Build Artifact
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: '23'
          distribution: 'temurin'
          cache: maven
      - name: Package the project
        run: mvn --batch-mode clean package -DskipTests
      - name: Upload built artifact
        uses: actions/upload-artifact@v4
        with:
          name: packaged-artifact
          path: target/*.jar

  deploy:
    needs: build-artifact
    if: github.ref == inputs.branch
    uses: ./.github/workflows/cd.yml  # Calls the reusable CD workflow
    with:
      artifact-name: "packaged-artifact"
    secrets: inherit
